[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-utp"
version = "250113"
description = "null"

[project.entry-points."endstone"]
utp = "endstone_utp:utp"