name: Update Clone Count

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Get clone count
        run: |
          CLONE_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/traffic/clones | jq -r '.count')
          echo $CLONE_COUNT > clone_count.txt
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clone_count.txt
          git commit -m "Update clone count"
          git push
